apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: release-longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.9.2
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true 
    automated:
      enable: true
      selfHeal: true
      prune: true
