apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mujak-my-id
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: irki@mujak.my.id
    privateKeySecretRef:
      name: mujak-my-id
    solvers:
      - dns01:
          cloudflare:
            email: irki@mujak.my.id
            apiTokenSecretRef:
              name: cloudflare-secrets
              key: api-token
