apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: release-nginx-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.1
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true 
    automated:
      enable: true
      selfHeal: true
      prune: true
