controller:
  service:
    loadBalancerIP: 10.227.4.199
  allowSnippetAnnotations: true
  config:
    annotations-risk-level: Critical
    enable-metrics: "true"
    metrics-port: "10254"
    metrics-per-host: "true"
  use-forwarded-headers: "true"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
    prometheusRule:
      enabled: true
  podAnnotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"