---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: release-loki
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true 
    automated:
      enable: true
      selfHeal: true
      prune: true
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.6.6
    helm:
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-04-01"
                object_store: filesystem
                store: tsdb
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          limits_config:
            retention_period: 48h
            ingestion_rate_mb: 50
            ingestion_burst_size_mb: 1000
            per_stream_rate_limit: 5MB
            per_stream_rate_limit_burst: 20MB
          compactor:
            working_directory: /var/loki/boltdb-shipper-compactor
            delete_request_store: filesystem
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
          storage:
            type: filesystem
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1
          persistence:
            size: 5Gi
            storageClass: longhorn
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
