---
- name: Create containerd kernel modules configuration
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf
    mode: '0644'

- name: Load overlay kernel module
  ansible.builtin.modprobe:
    name: overlay
    state: present

- name: Load br_netfilter kernel module
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present
