apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: storage
    name: in-cluster
  project: default
  source:
    path: argocd/apps/storage/longhorn
    repoURL: git@github.com:muwujak/mrscraper-infra.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      enable: true
      selfHeal: true
      prune: true
