---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: release-kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true 
    automated:
      enable: true
      selfHeal: true
      prune: true
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.11.0
    helm:
      values: |
        grafana:
          persistence:
            type: pvc
            enabled: true
            storageClassName: "longhorn"
            accessModes: ["ReadWriteOnce"]
            size: 500Mi
        alertmanager:
          alertmanagerSpec:
            retention: 6h
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: "longhorn"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 2Gi
        prometheus:
          prometheusSpec:
            retention: 7d
            storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: "longhorn"
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 5Gi
