grafana:
  persistence:
    type: pvc
    enabled: true
    storageClassName: "longhorn"
    accessModes: ["ReadWriteOnce"]
    size: 500Mi
alertmanager:
  alertmanagerSpec:
    retention: 6h
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec:
        volumeClaimTemplate:
        spec:
          storageClassName: "longhorn"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi