apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: release-metal-lb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.8
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true 
    automated:
      enable: true
      selfHeal: true
      prune: true
