apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: release-keda
  namespace: keda
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.18.0
    helm:
      values: |
        # Default values; customize as needed
        podIdentity:
          provider: none
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      enable: true
      selfHeal: true
      prune: true
